### ISSUE TITLE
Unclear font

### ISSUE THREAD

**Issue by nisan-abeywickrama** [cheyne-forgerson/raisingriver#2]
The font used in the navigation bar and other content is unclear.

**Comment by cheyne-forgerson** [comment]
Mr Eaves XL Modern from Adobe.

Do you have a suggestion to help clarify that?

**Comment by nisan-abeywickrama** [comment]
You are using **Mr Eaves XL Mod OT Thin**. You better change to **Mr Eaves XL Mod OT Light**.
Check it out here https://fonts.adobe.com/fonts/mr-eaves-xl
I recommend using google fonts

**Comment by cheyne-forgerson** [comment]
Thanks for the advice. The branding agency recommended thin, but definitely am having some issues with display.  Couldn’t find a google fonts equivalent.
